<div class="container">
    <div class="row">
        <h2 class="h2"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
    <?php $this->renderView('alerts/_success'); ?>
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">Micro Framework</h1>
            <p>
                Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec rutrum congue leo eget malesuada.
                Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
                Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Lorem ipsum dolor sit amet,
            </p>
            <p>
                Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec rutrum congue leo eget malesuada.
                Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
                Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Lorem ipsum dolor sit amet,
            </p>
        </div>
    </div>
</div>