<?php if ($this->view->message) : ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button class="close" type="button" data-dismiss="alert" aria-label="Cloes">
            <span aria-hidden="true">&times;</span>
        </button>
        <?php if (is_array($this->view->message)) {
            foreach ($this->view->message as $message) { ?>
                <p> <i class="fa fa-check"></i><?php echo $message; ?></p>
            <?php  } ?>
        <?php } else {  ?>
            <p> <i class="fa fa-check"></i><?php echo $this->view->message ?></p>
        <?php } ?>
    </div>
<?php endif; ?>