<div class="container">
    <h1 class="h1"><?php echo $this->getPageTitle(); ?></h1>

    <form action="/posts/<?php echo $this->view->post->id; ?>/update" method="POST" accept-charset="utf-8">
        <div class="form-group">
            <label for="title">Titulo</label>
            <input type="text" name="title" class="form-control" value="<?php echo $this->view->post->title; ?>">
        </div>

        <div class="form-group">
            <label for="title">Conteudo</label>
            <textarea class="form-control" name="content" id="content" cols="30" rows="10"><?php echo $this->view->post->content; ?></textarea>
        </div>
        <a href="/posts" class="btn btn-default">Cancela</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>