<div class="container">
    <div class="row">
        <h1 class="h1"><?php echo $this->getPageTitle(); ?>
            <a class="btn btn-primary pull-right" href="/posts/create"><i></i>Novo post</a>
        </h1>
    </div>

    <?php foreach ($this->view->posts as $post) : ?>
        <div class="row">
            <h3 class="h3"><a href="/posts/<?php echo $post->id; ?>/show"><?php echo $post->title; ?></a></h3>
            <p class="text-justify"><?php echo $post->content ?></p>
            <p class="text-right">
                <a href="/posts/<?php echo $post->id;?>/edit" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
            </p>
        </div>
        <hr>
    <?php endforeach; ?>
</div>