<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Microframework</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/posts">Posts</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <?php if ($this->auth->check()) : ?>
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->auth->name(); ?></span></a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </li>

       
      <?php else :  ?>
        <li class="nav-item ">
          <a class="nav-link " href="/login">Login</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/user/create">Register</a>
        </li>
      <?php endif; ?>
    </ul>
  </div>
</nav>